version: '3.8'

services:
  yolo-realtime:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo-realtime
    runtime: nvidia
    shm_size: '8gb'
    privileged: true  # Required for camera access
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONPATH=/workspace
      # CUDA optimization
      - CUDA_CACHE_MAXSIZE=2147483647
      - CUDA_CACHE_DISABLE=0
      - CUDA_FORCE_PTX_JIT=1
      # Memory optimization
      - CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
    volumes:
      - ./app:/workspace/app
      - ./data:/workspace/data
      - ./models:/workspace/models
      - ./results:/workspace/results
      - ./logs:/workspace/logs
      - ./configs:/workspace/configs
      # X11 forwarding for display
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      # Device access
      - /dev/video0:/dev/video0
    devices:
      # GPU devices
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      # Video devices
      - /dev/video0:/dev/video0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, video]

  monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo-monitoring
    depends_on:
      - yolo-realtime
    volumes:
      - ./logs:/workspace/logs
      - ./results:/workspace/results
    command: python3 app/monitoring_service.py

  visualization:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo-visualization
    ports:
      - "8050:8050"  # For Dash visualization
    volumes:
      - ./results:/workspace/results
      - ./logs:/workspace/logs
    command: python3 app/visualization_service.py

networks:
  default:
    driver: bridge